- bytecomp/translcore.ml
Before:
```
Fatal error: exception File "bytecomp/translcore.ml", line 948, characters 9-15: Assertion failed
```
After:
```
- : unit = ()
```
> Fix assertion failure for 'effect E _ ->'

- byterun/config.h
- byterun/platform.c
* minor heap size overflow in caml_init_domain
* caml_mem_round_up_pages type missmatch
> Fix error on IA32

- .travis-ci.sh
- .travis.yml
- byterun/fiber.c
* Reverts the unnecessary `CAMLlocals` introduced in ocamllabs/ocaml-multicore@57237fc.
* Edits travis build scripts for simple 32- and 64-bit builds.
> Remove unnecessary caml locals. Edit travis scripts for 32- and 64-bit builds.

- byterun/interp.c
Promoting an object duplicates the object in the major heap and uses write barriers to ensure that the copies are in sync. However, physical equality breaks due to this duplication. Physical equality is essential for pattern matching polymorphic and extensible variants. See #7 for example. The fix ensures that the major heap object is always used when comparing promoted objects.
This fix is certainly not ideal since it adds a branch to every integer equality! We might perhaps add a special instruction for physical equality. This PR fixes #7.
> Make physical equality aware of promotion duplication.

- byterun/domain.c
- byterun/memory.c
- byterun/platform.h
- byterun/shared_heap.c
Since the `is_main` field was always 0, lock on `pool_freelist` was used without being uninitialized [1] leading to mutual exclusion failures. This was the cause of strange behaviors with pools such as cycles, and the source of segfaults in #15. This in combination with the PR #18 fixes #15.
This PR additionally sets the owner of released pools to be NULL in order to better track ownership.
[1] https://github.com/ocamllabs/ocaml-multicore/blob/821b653592ddca80278e82903100deeb5934b6c2/byterun/shared_heap.c#L84
> Fixing is_main initialization in create_domain.

- byterun/fiber.c
- byterun/fiber.h
- byterun/minor_gc.c
As a part of promoting the stack, objects pointed to by the stack should also be promoted. This commit fixes a bug that ignores the latter if the stack is on a minor heap; `caml_scan_dirty_stack` only scans dirty stack whereas stacks in a minor heap are never marked as dirty. The fix always scans the stack, and also marks it clean since the stack no longer points to a minor heap.
The unconditional stack scanning can be optimized by only scanning the stack if the stack is in the minor heap or in the major heap and is marked as dirty.
> Fix stack promotion.

- byterun/fiber.c
When a stack is realloc’ed, it is worth resetting the old stack contents to avoid space leaks. Since the stack is being realloc’ed, it is currently running. Hence, no references to this stack from other heap objects are “useful”; such a reference cannot be used to resume the continuation represented by this stack, which would violate the one-shotness. If the program carries around such references, it would constitute a space leak. Resetting the stack avoids the need for the GC to scan the old copy of the realloc'ed stack.
> Reset realloc'ed stack to avoid useless scanning.

- byterun/fiber.c
Adds missing `caml_clean_stack_domain` for native code. This fixes #21.
> Added missing function for native code.

- byterun/interp.c
If caml_parent_stack was reset to NULL, then the link between parent and child fiber is severed if the child performs a C call which in turn calls back into OCaml. See the example here [1]. Build the example as `make COMP=MULTI`. With the fix you should see:
[Caml] Call caml_to_c
[C] Enter caml_to_c
[C] Call c_to_caml
[Caml] Enter c_to_caml
[Caml] Handle effect E. Continuing..
[Caml] Leave c_to_caml
[C] Return from c_to_caml
[C] Leave caml_to_c
[Caml] Return from caml_to_c
and without it:
[Caml] Call caml_to_c
[C] Enter caml_to_c
[C] Call c_to_caml
[Caml] Enter c_to_caml
Fatal error: exception Unhandled
> Do not initialize caml_parent_stack in caml_interprete

- byterun/domain.c
Without the fix, the minor heap area of a domain overlaps with the TLS area of the subsequent domain. For example, here is the debug output from `caml_init_domains`:
```
[-1] Initial stack limit: 8192k bytes
[-1] caml_init_domains[0]: tls_start=0x7f9200000000 tls_end=0x7f9200001000 minor_start=0x7f9200002000 minor_end=0x7f9201002000
[-1] caml_init_domains[1]: tls_start=0x7f9201000000 tls_end=0x7f9201001000 minor_start=0x7f9201002000 minor_end=0x7f9202002000
[-1] caml_init_domains[2]: tls_start=0x7f9202000000 tls_end=0x7f9202001000 minor_start=0x7f9202002000 minor_end=0x7f9203002000
[-1] caml_init_domains[3]: tls_start=0x7f9203000000 tls_end=0x7f9203001000 minor_start=0x7f9203002000 minor_end=0x7f9204002000
[-1] caml_init_domains[4]: tls_start=0x7f9204000000 tls_end=0x7f9204001000 …
```
> Prevent overlap between adjacent domains' TLS and minor heap areas

- byterun/alloc.c
- byterun/array.c
- byterun/caml/alloc.h
- byterun/caml/domain.h
- byterun/caml/memory.h
- byterun/caml/misc.h
- byterun/floats.c
- byterun/interp.c
- byterun/major_gc.c
Add the convenience functions `caml_alloc_<n>`, and simplify how `Alloc_small` works.
> Alloc API changes (1/2)

- byterun/addrmap.c
- byterun/caml/addrmap.h
- byterun/caml/shared_heap.h
- byterun/major_gc.c
- byterun/shared_heap.c
If the mark stack overflows, find some pools that occur frequently in the mark stack and mark those as needing rescanning.
> Handle mark stack overflow by postponing marking of some pools.

- byterun/caml/misc.h
I believe the macro 'Assert' was wrongly defined inside a private zone in misc.h. I have moved the macro into public space.
> Moved macro 'Assert' from private zone into public space in misc.h

- .travis-ci.sh
- testsuite/Makefile
- testsuite/disabled
- testsuite/makefiles/summarize.awk
- testsuite/tests/asmcomp/Makefile
- testsuite/tests/asmcomp/amd64.S
- testsuite/tests/asmcomp/main.c
- testsuite/tests/asmcomp/run.ml
- testsuite/tests/callback/Makefile
- testsuite/tests/gc-roots/globrootsprim.c
- testsuite/tests/typing-extensions/extensions.ml.reference
Get the testsuite into slightly better shape. Disables several tests that aren't expected to work at the moment, but there are still 14 failing tests. Most of these are actually about weak references or marshalling, and should probably be moved into a different directory.
> Testsuite fixes

- asmcomp/amd64/emit.mlp
- asmrun/amd64.S
Gdb now reports sane backtraces at "every" instruction. The intended behaviour is that the backtrace stops at 
- top of fiber stack or
- bottom of C frame at external calls (`caml_c_call`) or
- `caml_start_program` when setting up the main OCaml program or callbacks. 
Being sane at "every" instruction ensures that code that might unwind the stack, such as profilers do not segfault due to corrupted frames at the bottom of the stack. gproftools/cpu-profiler now works on multicore!
The main trick is to ensure that the return address of the last frame is `NULL`. Debuggers and other unwinding code treats them as a signal to stop unwinding. We do this by carefully constructing CFI information such that they point to a known location which is guaranteed to be NULL. See `OCAMLCFAXXX` and …
> Fix CFI in amd64.

- byterun/minor_gc.c
Removes the recursion in oldify_one and drops a few levels of indentation.
Best read with [whitespace not shown in diff](https://github.com/ocamllabs/ocaml-multicore/pull/153/files?w=1)
> Refactor minor GC handling of Infix_tag

- byterun/caml/domain.h
- byterun/domain.c
- byterun/major_gc.c
- byterun/minor_gc.c
Poll for interrupts between minor and major slice, and between sweeping
and marking. This PR also fixes broken threadscope output from earlier PR.
> Improve stealing by polling for interrupts more frequently.

- byterun/caml/shared_heap.h
- byterun/major_gc.c
- byterun/shared_heap.c
Various optimisations to the marking loop, mainly to avoid unnecessarily touching too many bits of memory in the inner loop. Best read commit-by-commit.
On my machine, one iteration of gcstress goes from ~650ms before this patch to ~480ms afterwards.
> Marking optimisations

- byterun/Makefile.common
The `.tbl` files are [included by installed headers](https://github.com/ocamllabs/ocaml-multicore/blob/9749637d6642b48f330483a73c41c336713fbc47/byterun/caml/domain_state.h#L17), so they need to be installed, too.
> Install .tbl files.

- byterun/caml/memory.h
- byterun/caml/platform.h
- byterun/domain.c
- byterun/fiber.c
- byterun/memory.c
- byterun/minor_gc.c
- testsuite/tests/parallel/domain_id.ml
Fix a bug with handling of Infix tag objects being pointed to from
remebered major refs at the end of minor GC.
Introduce num_domains_running variable that keeps track of the same. Use
this for non atomic versions of atomic operations when only one domain
is running.
Remove suspect `caml_darken`s in minor_gc.c.
> Various improvements and fixes.

- byterun/domain.c
- testsuite/tests/parallel/join.ml
The test used multiple `incr` from different threads with no sync.
Instead, use an array of separate flags.
Also, squash a warning by using an exception other than Failure
when matching on a particular string.
> Fix a race condition in parallel/join.ml.

- testsuite/tests/effects-disallowed/Makefile
- testsuite/tests/effects-disallowed/when_test.ml
- testsuite/tests/effects-disallowed/when_test.ml.reference
- typing/typecore.ml
.. by making the continuation variable inaccessible in `when` expressions. The fix is rather simple, we keep two typing environments live `ext_env` and `ext_env'`, where the latter is an extension of the former with the continuation variable bound. We use `ext_env` when typing the `when` expression, and `ext_env'` when typing the clause body.
> Fixes issue 204

- asmcomp/amd64/emit.mlp
This patch runs the profiling function `mcount` as a C extcall, using the system stack instead of fiber stacks. The `mcount` primitive only needs to see a return address at `*(rsp)` and a second return address at `*(rbp + 8)`, and never inspects the stack, so it doesn't care what stack it runs on.
This makes the profile slop space unnecessary. I'll send a separate PR to remove the slop space after #203 is merged, since otherwise there will be conflicts.
> When profiling is enabled, run mcount on the C stack.

- asmrun/amd64.S
- byterun/backtrace_prim.c
- byterun/callback.c
- byterun/caml/fiber.h
- byterun/caml/minor_gc.h
- byterun/debugger.c
- byterun/domain.c
- byterun/fiber.c
- byterun/interp.c
- byterun/major_gc.c
- byterun/meta.c
- byterun/minor_gc.c
- byterun/shared_heap.c
- byterun/startup.c
- otherlibs/systhreads/st_stubs.c
- otherlibs/threads/scheduler.c
Now that stacks no longer move during GC, it's safe to store stack pointers directly rather than as offsets. This simplifies the computations necessary to restore stack pointers in amd64.S.
This makes `caml_extern_sp` redundant, so it's removed. That makes `caml_save/restore_stack_gc` no-ops, so they're gone too.
> Stack pointer refactor

- bytecomp/translcore.ml
- bytecomp/translmod.ml
- Read barriers were done on references to global constants
in native code due to a missed case in translmod.ml
- Read barriers were done on loads of int refs due to a
missed optimisation in translcore.ml
> Improve performance by doing fewer read barriers.

- asmcomp/amd64/emit.mlp
- byterun/caml/config.h
- utils/domainstate.ml.c
This patch lowers Max_domains from 256 to 128, which makes the read barrier mask fit in a sign-extended 32-bit immediate constant. This saves code size on x86-64, replacing a 13-byte sequence:
movabs MASK64, %rdx
test %rdx, %rax
with a 6-byte sequence:
test MASK32, %rax
> Shorten read barrier code on x86-64

- asmcomp/amd64/emit.mlp
- asmrun/amd64.S
- asmrun/backtrace_prim.c
- asmrun/fail.c
- asmrun/startup.c
- byterun/callback.c
- byterun/caml/domain_state.tbl
- byterun/fiber.c
This patch uses %r14 on amd64 to access globals, simplifying the assembly stubs and shortening the code needed for making allocations and C calls.
For reviewing: the first commit makes a nontrivial change, moving the current exception handler from %r14 to a field in Caml_state, and changing how the offsets are computed. The other commits are mechanical.
> R14 globals

- asmrun/startup.c
- byterun/backtrace_prim.c
- byterun/caml/compatibility.h
- byterun/caml/domain_state.tbl
- byterun/caml/fiber.h
- byterun/debugger.c
- byterun/domain.c
- byterun/fiber.c
- byterun/instrtrace.c
- byterun/interp.c
- otherlibs/systhreads/st_stubs.c
stack_high is now redundant (after #215), so it's removed. That makes `load_stack`, `save_stack`, `caml_restore_stack` and `caml_init_main_stack` trivial, so they're inlined & removed.
> Remove stack_high and cleanup

- byterun/roots.c
Trunk OCaml scans newly-initialised globals during minor GC, as
they may contain newly-allocated minor objects. Multicore deleted
the tracking of which globals were newly initialised, as the
synchronisation of this variable was tricky.
So, multicore scans all globals during minor GC. This was a
temporary hack, with the better fix being to make initialisation
of globals promote before initialisation, so that newly-initialised
globals never contain minor heap pointers.
The better fix got implemented, but I forgot to remove the hack,
so minor GC has been uselessly scanning globals for quite a while.
This commit removes the unnecessary scan.
> Fix a missed optimisation in root scanning.

- stdlib/domain.mli
Makes it clear these need to be called in a critical section
> doc changes for wait_for and wait_until

- byterun/caml/domain_state.tbl
- byterun/domain.c
- byterun/globroots.c
- byterun/memory.c
Read fault return value field used to be a local root. It certainly needs to be a root since a GC may occur after the return value field is set. But the return value field is written to by a different domain different from the domain issuing the read fault request. The domain issuing the read fault request has the return value field in its local root set. This introduces a data race between the remote domain writing the return value of a read fault to the field and a minor GC (specifically, `oldify_one`) in the read fault issuing domain writing the default value (`Val_unit`) to the field. The race may overwrite the result written by the remote domain.
The fix is to make the read fault return value field a global root, which is only scanned when all the domains are blocked at the beginning …
> Read fault return value is made a global root.

- byterun/major_gc.c
Tested this branch against the `queens_segfault` branch on sandmark and no longer see the segfault.
> fix segfault in major_gc. Fixes #247

- byterun/memory.c
- testsuite/tests/parallel/atomics.ml
`caml_atomic_exchange` didn't call the write barrier if the atomic being modified was young. But because of the young-young table, we need to do work in the write barrier even when mutating young objects.
I suspect this isn't the only codepath that has this bug: the assumption that the write barrier does no work when young values are modified is easy to make, because it's true in stock OCaml.
> Fix #252 by making atomic exchange always call the write barrier.

- asmcomp/afl_instrument.ml
- asmcomp/amd64/selection.ml
- asmcomp/arm/selection.ml
- asmcomp/cmm.ml
- asmcomp/cmm.mli
- asmcomp/cmmgen.ml
- asmcomp/i386/selection.ml
- asmcomp/printcmm.ml
- asmcomp/selectgen.ml
- asmcomp/spacetime_profiling.ml
- asmcomp/strmatch.ml
- bytecomp/bytegen.ml
- bytecomp/lambda.ml
- bytecomp/lambda.mli
- bytecomp/printlambda.ml
- bytecomp/semantics_of_primitives.ml
- bytecomp/translcore.ml
- testsuite/tests/asmcomp/parsecmm.mly
This PR aims to fix #237. `Atomic.get` is a library function that provides atomic reads across domains. On `x86`, these atomic reads emit an external function call - `caml_atomic_load`. This function loads a value and emits a `read_barrier` to prevent re-ordering from happening. 
The external call is unnecessary, and on `x86`, can be translated to plain loads.
TODO: 
`Patomic_load` is a lambda op, which has been extended with a field to denote whether that load is to a value or an immediate.
```
| Patomic_load
```
to
```
| Patomic_load of {immediate_or_pointer : immediate_or_pointer}
````
`Cload` and `Cloadmut` are two `cmm` operations defined as - 
```ocaml
| Cload of memory_chunk * Asttypes.mutable_flag
| Cloadmut
```
This has now been modified to be - 
```ocaml
| Cload of …
```
> Inlining loads in the native code

- asmcomp/cmmgen.ml
- bytecomp/translcore.ml
- stdlib/atomic.mli
Adding an entry in `translcore.ml` to specialize loads based on whether the load is to an `immediate` or `pointer`
> Inline loads specialized

- asmrun/amd64.S
changes to the PUSH_EXN_HANDLER/POP_EXN_HANDLER assembly to avoid some problematic depdendencies between instructions
> changes to the PUSH_EXN_HANDLER/POP_EXN_HANDLER assembly

- byterun/caml/domain.h
- byterun/caml/major_gc.h
- byterun/caml/memory.h
- byterun/caml/signals.h
- byterun/domain.c
- byterun/fiber.c
- byterun/finalise.c
- byterun/globroots.c
- byterun/major_gc.c
- byterun/memory.c
- byterun/minor_gc.c
- byterun/platform.c
- byterun/shared_heap.c
- byterun/signals.c
- byterun/weak.c
Fixes for issue #129
Modified the calls in create_domain to use non-raising variants (caml_stat_alloc_noexc instead of caml_stat_alloc), and added some cleanup error handling in the case of failure.
> Fixes for error handling during domain creation 

- byterun/caml/memory.h
As it stands Caml_state points to a thread local global. Examining the hot assembly for some of the microbenchmarks it looks like this is looked up multiple times in the compiled code.
Caching a pointer to Caml_state at the start of a method eliminates these and shortens the sequence of generated instructions for the CAML* macros.
This has the most impact on the test_many_args_noalloc and test_many_args_alloc microbenchmarks which see a 10% reduction in runtime.
> cache local roots pointer to avoid needing to look it up each time

- byterun/caml/minor_gc.h
- byterun/minor_gc.c
- testsuite/tests/lazy/minor_major_force.ml
- testsuite/tests/lazy/minor_major_force.reference
This PR fixes a problem found with how the minor GC handles Lazy blocks that have been forced to `Forward_tag` and are in the remembered set. 
There is a testcase that demonstrates the issue in `testsuite/tests/lazy/minor_major_force.ml`. This sets up a record on the major heap with a mutable lazy field. It then forces this lazy value to forward to a value on the minor heap. When the minor GC code comes to atomically update the reference set pointers, the existing implementation will insert a pointer to the minor heap rather than the value on the major heap. 
This PR fixes this bug by adding a list `major_ref_rewrites` which contains the correct pointers to the heap as determined by `oldify_one`. It then applies these values atomically in the `minor_gc/update_minor_tables` stage of the …
> Fix a bug with Lazy values in remembered set

- asmcomp/amd64/emit.mlp
Fixes the DWARF CFI for non-allocating external calls. Consider this program:
```ocaml
let foo () =
classify_float 1.0;
print_string "Hello, world!"
let _ = foo ()
```
In master, backtrace at the entry to `caml_classify_float_unboxed` used to produce a corrupted backtrace:
Now it produces the correct backtrace:
The position of frames `#1` and `#2` are swapped; Ideally, `<signal handler called>` should come before `camlTest__foo_1002`, to indicate the boundary between OCaml and C. But this is not important for correctness and will not be fixed. 
I have fixed the implementation in the `emit_profile` function as well, although `emit_profile` is not safe to be called in multicore since we may stack overflow in OCaml calling `mcount` directly. But that's a separate problem.
> Fix DWARF CFI for non-allocating external calls

- byterun/caml/major_gc.h
- byterun/domain.c
- byterun/major_gc.c
- byterun/shared_heap.c
This PR fixes a couple of space leaks that were exposed by some domain spawning/terminating stress tests.
The first set are per-domain structures that failed to be cleaned up on termination - these are all in `domain.c`.
The second issue is in `pool_find` in `shared_heap.c` which does not currently check the global pools when looking for a new pool. In discussions with @stedolan this seems to have been a bug rather than a deliberate design choice. This PR fixes that by searching for pools in the global list that have some space or could be swept to clear some up.
The third issue that gets fixed is a GC pacing one. Right now if domains are very short lived (as they are in this stress test), we don't factor in allocations they did during their brief existence and this means we don't sweep …
> Fix for a few space leaks

- byterun/caml/domain_state.tbl
- byterun/domain.c
- byterun/major_gc.c
The motivation behind this PR comes from experiencing a segfault during stress testing that was traced back to a pool being rescanned while another domain was allocating in to it. To address this the pools to rescan are now moved to a domain local list which ensures this case is no longer possible.
> move from a global pools_to_rescan to a domain-local one

- byterun/globroots.c
- byterun/major_gc.c
- byterun/obj.c
- byterun/roots.c
Reverts ocaml-multicore/ocaml-multicore#276. The global roots are plain old-linked lists, which are already incrementally scanned. Even if multiple domains race to scan it, the head of the list will be added to every domain, one of the domain will win the race to mark the first object. Other domains will not do any more work.
> Revert "Let only one domain scan the globals"

- byterun/weak.c
This PR fixes an assert in caml_ephe_clean where we check that blocks not released are marked. We saw this fail on some multicore machines in `ephetest_par` with the stop-the-world minor gc branch.
> Fix assert in caml_ephe_clean

- byterun/major_gc.c
- byterun/shared_heap.c
Allow mark stack to be small initially and then grow until it is 1/32 of
the size of the shared heap on a domain. At that point, prune the mark
stack to limit the size of the growth.
> Give more space for mark stack.

- byterun/major_gc.c
This PR bumps up MARK_STACK_INIT_SIZE which must be larger than POOL_WSIZE. If this isn't done, it is possible for a domain to get into a loop where it tries to realloc and prune the mark stack, but will never have a mark stack size big enough to mark a pool.
> Fix for mark stack being too small

- byterun/misc.c
This PR cleans up `caml_gc_log` to check that `fflush` is only called when it GC logging is enabled. 
This makes the implementation match `caml_gc_message`.
> Do fflush and variable args in caml_gc_log only when enabled

- byterun/caml/domain_state.tbl
- byterun/caml/major_gc.h
- byterun/domain.c
- byterun/major_gc.c
This PR alters major collection slice to allow an 'opportunistic' collection which can be called from `caml_ml_domain_yield*`. We want to change the behaviour with the yield functions because as things stand, repeated calls to the yield function cause the GC to continually change phase and this causes interrupts on other domains. 
The opportunistic slice does not change the phase of the GC. It introduces a credit for work done that is then offset when a standard major GC slice is performed. 
This provides the basis in the future for doing opportunistic major mark and sweep work while waiting for synchronization with other domains.
> Introduce an 'opportunistic' major collection slice fn

- byterun/eventlog.c
This PR bumps the EVENT_BUF_SIZE to reduce the number of times the buffer is flushed which can be useful when debugging with event trace data.
> Bump EVENT_BUF_SIZE in eventlog.c to 32768

- byterun/caml/memory.h
- byterun/caml/mlvalues.h
- byterun/memory.c
This PR makes some optimizations to the `write_barrier` driven by benchmarking results on `chameneos_redux_lwt` in sandmark. 
It makes 3 changes:
- inlines the write_barrier into the call sites in memory.c
- use intnat for field indexes
- match the branching logic in 4.06.1 `caml_modify` more closely
With these changes I see `chameneos_redux_lwt`:
- 4.06.1: ~1.50s
- multicore (baseline): ~2.00s
- multicore (with this change): ~1.85s
> write_barrier optimizations

- asmcomp/cmmgen.ml
Mark `caml_atomic_exchange`, `caml_atomic_fetch_add` and `caml_atomic_cas` as non-allocating in cmmgen.ml
Brings things into line with: https://github.com/ctk21/ocaml-multicore/pull/25
> Make caml_atomic_* non-allocating in cmmgen.ml

- byterun/custom.c
- byterun/major_gc.c
- byterun/minor_gc.c
- byterun/shared_heap.c
This PR alters the accounting for sweep work to be all in word size. At present there appears to be a discrepancy between large alloc and pool sweep work:
- The budget is setup here in blocks: https://github.com/ocaml-multicore/ocaml-multicore/blob/master/byterun/major_gc.c#L340
- The sweep work for pools is in blocks: https://github.com/ocaml-multicore/ocaml-multicore/blob/master/byterun/shared_heap.c#L428
- The sweep work for large allocs is in word size: https://github.com/ocaml-multicore/ocaml-multicore/blob/master/byterun/shared_heap.c#L458
> Unify sweep budget to be in word size units

- byterun/major_gc.c
Minor fix to make sure budget_left is updated with opportunistic slices. 
Prevents busy spinning when no work to do, for example when called from: https://github.com/ocaml-multicore/ocaml-multicore/blob/master/byterun/domain.c#L1037
(fix by @stedolan for stw ported here)
> Always update budget_left in major_collection_slice

- byterun/shared_heap.c
This PR fixes `large_alloc_sweep` to run the finalizers when we sweep large alloc blocks.
> Run finalizers for Custom blocks in large_alloc space

- byterun/domain.c
This PR changes the Chunk size for opportunistic mark work in the domain yield functions to be 0x400 (1024) rather than 0x10000 (65536).
> Make Chunk_size for opportunistic mark work 

- byterun/major_gc.c
This PR prevents long pauses that can occur with domain termination.
This mirrors: https://github.com/ctk21/ocaml-multicore/pull/40
> Handle interrupts in caml_finish_marking & caml_finish_sweeping 

- byterun/major_gc.c
"Handle interrupts in caml_finish_marking & caml_finish_sweeping "
> Revert #300

- byterun/caml/platform.h
- byterun/platform.c
- Do a trylock instead of a blocking section in With_mutex
- Inline some lock-handling functions
This roughly doubles the throughput of this terrible program:
```
let () =
for i = 0 to 1000_000_000 do
print_char 'a'
done
```
> Locking optimisations for I/O

- byterun/major_gc.c
We used to incorrectly count the cost for every field of the object to be the size of the object (`      budget -= Whsize_hd(hd);` was in the body of the while loop which iterates over each field`). This PR fixes the behavior. This PR improves the max latency of menhir.ocamly from 634 ms to 526 ms.
> Account correctly for incremental mark budget

- asmcomp/polling.ml
Reverts ocaml-multicore/ocaml-multicore#302
Causes segfaults on test_decomress on multiple cores.
> Revert "more safepoints"

- asmcomp/asmgen.ml
- asmcomp/polling.ml
Safepoint insertion was generating bad frametables, by using liveness information from after regalloc had clobbered it. This patch moves the polling insertion to just after liveness computation, and restores #302
> More safepoints again

- byterun/major_gc.c
This PR checks interrupts during `caml_empty_mark_stack` and `caml_finish_sweeping` which can improve pause times when main domains are running. 
It mirrors: https://github.com/ctk21/ocaml-multicore/pull/43
And is a second attempt after the bad #300
> Check interrupts during caml_empty_mark_stack and caml_finish_sweeping

- byterun/memory.c
- opam
This PR is not necessary for stw_minor_gc
> Writes in caml_blit_fields should always use caml_modify_field to record young_to_young pointers

- byterun/caml/weak.h
- byterun/weak.c
Multicore assumes that newly allocated ephemerons need not be marked or flushed in the cycle that they were allocated. The ephemerons themselves are allocated Marked. But can the keys or data be unmarked? Yes they can. `blit` operations copy weak references from one ephemeron to another without marking them. If the keys, for example, remain unmarked at the end of the marking phase, then the newly allocated ephemeron should sweep those keys to get rid of them in the same phase.
The fix is to mark the keys that are being blited. This will keep the unreachable keys alive for one more major cycle. Alternatively, we could have swept the newly allocated ephemerons in the cycle in which they were allocated. But this introduces a race between ephemeron sweeping and mutator allocating new …
> Fix bug with Weak.blit

- byterun/domain.c
Moving the `num_domains_running` decrement allows us to rely on `caml_domain_alone()` in the shared heap teardown. This means we can add fast-paths for the single domain case in the new lockfree pools code that's incoming.
> move num_domains_running decrement

- tools/eventlog_to_latencies.py
A script to generate GC latency report from eventlog. Here's an example:
```bash
$ python3 eventlog_to_latencies.py ~/temp/eventlog.16343.json                                                                      [14/779]
Mean latency = 1210944.3816942552 ns            
Max latency = 28443132 ns                     
Percentile, Latency(ns)                         
10,1643                                       
20,2848                                         
30,5910                                         
40,12347                                        
50,30388                                        
60,113719                                     
70,457042                                     
80,2336664                                      
90,4018943 …
```
> Added eventlog_to_latencies.py to tools

- asmcomp/closure.ml
- asmcomp/cmmgen.ml
Effect handler primitives were translated to C calls in lambda to
Clambda conversion (`asmcomp/closure.ml`). Since flambda does not go
through this translation phase, the effect handler primitives were kept
around and the compilation fails at cmmgen where the cmmgen pass
observes an unexpected primitive.
The fix is to do the translation at cmmgen rather than the lambda to
clambda conversion.
> Get multicore compiler working with flambda.

- bytecomp/matching.ml
Add the missing case for `forcing_tag`.
> Add a missing case for handling lazy values in matching.ml
